### ISSUE TITLE
bytes - str error

### ISSUE THREAD

**Issue by Pomid0rchik** [Revise7/ViperVenom#5]
The program displays error of type conversion in PayloadGenerator...
```
File "C:\Users\User\source\repos\ViperVenom\ViperVenom.py", line 558, in <module>
    PayloadGenerator()
  File "C:\Users\User\source\repos\ViperVenom\ViperVenom.py", line 303, in PayloadGenerator
    malfile.write(f'''
TypeError: a bytes-like object is required, not 'str'
```

After writing the generator parameters and hitting "run" this is what it displays me.

**Comment by 0x4Hydro** [comment]
Hi, 

Thanks for bringing this issue to our attention, we are aware that the software has this bug after a new Python update, we have fixed this issue and we will release an update on Saturday.

Thanks again,

Itay.
